name: Code check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  code-check:

    runs-on: ubuntu-latest
    container:
      image: wdtilburg/bitbucket-pipelines-php81

    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        run: composer install
      - name: Phive install
        run: phive --no-progress install --force-accept-unsigned --trust-gpg-keys 4AA394086372C20A

      - name: Setup test environment
        run: bin/init_test_environment.sh

      - name: Cache clean
        run: bin/console cache:clear --env=test
      - name: Cache warmup
        run: bin/console cache:warmup --env=test

      - name: PHP Mess Detector - global
        run: vendor/bin/phpmd src text phpmd.xml
      - name: PHP Mess Detector - entities
        run: vendor/bin/phpmd src/Entity/ text phpmd-entities.xml

      - name: PHP Static Analysis
        run: vendor/bin/phpstan analyse --no-progress

      - name: PHP Coding Standards
        run: vendor/bin/php-cs-fixer fix --diff --dry-run

      - name: Install node 18.x
        run: n 18
      - name: Npm install
        run: npm install
      - name: Encore build
        run: mkdir -p public/build/app && chown -R 1001:1001 public/build && npm run build

      - name: PHP Unit test
        run: bin/phpunit

      - name: Behat test
        run: vendor/bin/behat

      - name: PHP Code Coverage - HTML Report
        run: vendor/bin/phpcov merge --html var/coverage-report/html var/coverage-report
      - name: PHP Code Coverage - XML Report
        run: vendor/bin/phpcov merge --clover var/coverage-report/coverage.xml var/coverage-report
      - name: PHP Code Coverage - Check
        run: bin/coverage-checker var/coverage-report/coverage.xml 100

      - name: PHP Security Checker
        run: bin/local-php-security-checker
