name: Deploy

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      deploy_env:
        type: choice
        description: 'Deploy Environment'
        required: true
        options:
          - 'm2test.wdtdemo.nl'
          - 'm2test-staging.wdtdemo.nl'

# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: production_environment

jobs:
  deploy-production:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy ${{ inputs.deploy_env }}
          deployer-binary: bin/dep
          private-key: ${{ secrets.PRIVATE_KEY }}
